server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://MONITORING_PRIVATE_IP:3100/loki/api/v1/push

scrape_configs:
  - job_name: taskflow-docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: taskflow-docker
          host: APP_PUBLIC_IP
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            service: service
            route: route
            method: method
            status_code: status_code
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          service:
          route:
          method:
          status_code:
